### ISSUE TITLE
Dockerfile fails to build

### ISSUE THREAD

**Issue by sparticvs** [Quobis/action-owasp-dependecy-track-check#12]
Hello! I'm having an issue with using the setup as the Dockerfile itself is failing to build with a go-lang error. https://github.com/sparticvs/cwssjs/actions/runs/5501790922/jobs/10025623123?pr=36 is the example job log.

**Comment by jacobtb23** [comment]
Getting the same error here.

 `[ERROR: failed to solve: process "/bin/sh -c go get github.com/ozonru/cyclonedx-go/cmd/cyclonedx-go && cp /root/go/bin/cyclonedx-go /usr/bin/" did not complete successfully: exit code: 2"`

**Comment by macarracedo** [comment]
Problem related with `packageurl-go` retrieval, which is needed in `cyclonedx-go.`

Showing output error when trying to build a docker image locally.
` => ERROR [3/6] RUN go get github.com/ozonru/cyclonedx-go/cmd/cyclonedx-go && cp /root/go/bin/cyclonedx-go /usr/bin/        303.8s 
------
 > [3/6] RUN go get github.com/ozonru/cyclonedx-go/cmd/cyclonedx-go && cp /root/go/bin/cyclonedx-go /usr/bin/:
#6 303.7 # cd .; git clone -- https://github.com/package-url/packageurl-go /root/go/src/github.com/package-url/packageurl-go       
#6 303.7 Cloning into '/root/go/src/github.com/package-url/packageurl-go'...
#6 303.7 fatal: unable to access 'https://github.com/package-url/packageurl-go/': Operation timed out after 300034 milliseconds with 0 out of 0 bytes received
#6 303.7 package github.com/package-url/packageurl-go: exit status 128
------
executor failed running [/bin/sh -c go get github.com/ozonru/cyclonedx-go/cmd/cyclonedx-go && cp /root/go/bin/cyclonedx-go /usr/bin/]: exit code: 1`

Exit code changes in second try from 1 to 2, as in @jacobtb23 mention

> Getting the same error here.
> 
> `[ERROR: failed to solve: process "/bin/sh -c go get github.com/ozonru/cyclonedx-go/cmd/cyclonedx-go && cp /root/go/bin/cyclonedx-go /usr/bin/" did not complete successfully: exit code: 2"`

Showing output error in second try.
` => ERROR [3/6] RUN go get github.com/ozonru/cyclonedx-go/cmd/cyclonedx-go && cp /root/go/bin/cyclonedx-go /usr/bin/          4.6s 
------
 > [3/6] RUN go get github.com/ozonru/cyclonedx-go/cmd/cyclonedx-go && cp /root/go/bin/cyclonedx-go /usr/bin/:
#5 4.435 # github.com/package-url/packageurl-go
#5 4.435 root/go/src/github.com/package-url/packageurl-go/packageurl.go:417:16: undefined: strings.Cut
#5 4.435 root/go/src/github.com/package-url/packageurl-go/packageurl.go:528:22: undefined: strings.Cut
#5 4.435 root/go/src/github.com/package-url/packageurl-go/packageurl.go:535:20: undefined: strings.Cut
------
executor failed running [/bin/sh -c go get github.com/ozonru/cyclonedx-go/cmd/cyclonedx-go && cp /root/go/bin/cyclonedx-go /usr/bin/]: exit code: 2`

**Comment by prabhushan** [comment]
Hi.. any update this? This is a blocker

**Comment by prabhushan** [comment]
@antonroman .. thanks for merging the code.. when is release available
