### ISSUE TITLE
Support for NuGet (.NET)  projects

### ISSUE THREAD

**Issue by antonroman** [Quobis/action-owasp-dependecy-track-check#3]
We need to be able to generate  BoM for .NET projects and upload them to the DTrack server.

We must use this tool: [https://github.com/CycloneDX/cyclonedx-dotnet](https://github.com/CycloneDX/cyclonedx-dotnet) and an opensource project as a testing reference.

Check also if .NET is supported in https://docs.dependencytrack.org/

**Comment by coderpatros** [comment]
Hi @antonroman, Dependency-Track supports all software ecosystems.

It's more about whether or not the configured sources for vulnerability information supports a particular ecosystem. And Sonatype OSS Index does include vulnerability information for .NET packages.

**Comment by macarracedo** [comment]
Skill properly added
