### ISSUE TITLE
Creates issues to support different languages

### ISSUE THREAD

**Issue by antonroman** [Quobis/action-owasp-dependecy-track-check#4]
We need to create an issue for each of the languages we are going to support:

- Cargo (Rust)
- Composer (PHP)
- Gems (Ruby)
- Hex (Erlang/Elixir)
- Maven (Java)

**Comment by macarracedo** [comment]
PHP, Java and Ruby support added.

**Comment by YunaBraska** [comment]
Plase add also Gradle, shouldn't be much difference than maven

**Comment by antonroman** [comment]
Ok, @YunaBraska  I created issue #10 to support Gradle projects.
I'm closing this one.
